"""ISO 3166-1 alpha-2 country normalization.

Victim-country values originate from free-form LLM extraction (see
llm/backend.py and research/investigate.py) and have no guaranteed shape:
an alpha-2 code, a full English name in any casing, or a common alias.
This module is the single normalization boundary used both anterograde
(on write, in db.py) and retrograde (one-time backfill in db._migrate).
"""

from __future__ import annotations

_CODE_TO_NAME: dict[str, str] = {}
_NAME_TO_CODE: dict[str, str] = {}


def _key(value: str) -> str:
    return " ".join(value.strip().lower().split())


def _register(code: str, *names: str) -> None:
    _CODE_TO_NAME.setdefault(code, names[0])
    _NAME_TO_CODE[_key(code)] = code
    for name in names:
        _NAME_TO_CODE[_key(name)] = code


def normalize_country(value: str | None) -> str | None:
    """Best-effort mapping of a free-form country string to its canonical
    ISO 3166-1 alpha-2 code. Returns None if empty or unrecognized."""
    if not value:
        return None
    key = _key(value)
    if not key:
        return None
    return _NAME_TO_CODE.get(key)


def country_name(code: str | None) -> str | None:
    """Canonical English short name for an alpha-2 code, else None."""
    if not code:
        return None
    return _CODE_TO_NAME.get(code.strip().upper())


# ── ISO 3166-1 alpha-2 table (code, canonical name, extra aliases) ─────────
# Aliases cover common short forms LLM extraction tends to produce.
_register("AD", "Andorra")
_register("AE", "United Arab Emirates", "UAE")
_register("AF", "Afghanistan")
_register("AG", "Antigua and Barbuda")
_register("AI", "Anguilla")
_register("AL", "Albania")
_register("AM", "Armenia")
_register("AO", "Angola")
_register("AQ", "Antarctica")
_register("AR", "Argentina")
_register("AS", "American Samoa")
_register("AT", "Austria")
_register("AU", "Australia")
_register("AW", "Aruba")
_register("AX", "Aland Islands")
_register("AZ", "Azerbaijan")
_register("BA", "Bosnia and Herzegovina")
_register("BB", "Barbados")
_register("BD", "Bangladesh")
_register("BE", "Belgium")
_register("BF", "Burkina Faso")
_register("BG", "Bulgaria")
_register("BH", "Bahrain")
_register("BI", "Burundi")
_register("BJ", "Benin")
_register("BL", "Saint Barthelemy")
_register("BM", "Bermuda")
_register("BN", "Brunei", "Brunei Darussalam")
_register("BO", "Bolivia")
_register("BQ", "Bonaire, Sint Eustatius and Saba")
_register("BR", "Brazil")
_register("BS", "Bahamas")
_register("BT", "Bhutan")
_register("BV", "Bouvet Island")
_register("BW", "Botswana")
_register("BY", "Belarus")
_register("BZ", "Belize")
_register("CA", "Canada")
_register("CC", "Cocos Islands", "Cocos (Keeling) Islands")
_register("CD", "Democratic Republic of the Congo", "DR Congo", "Congo-Kinshasa")
_register("CF", "Central African Republic")
_register("CG", "Congo", "Republic of the Congo", "Congo-Brazzaville")
_register("CH", "Switzerland")
_register("CI", "Cote d'Ivoire", "Ivory Coast")
_register("CK", "Cook Islands")
_register("CL", "Chile")
_register("CM", "Cameroon")
_register("CN", "China")
_register("CO", "Colombia")
_register("CR", "Costa Rica")
_register("CU", "Cuba")
_register("CV", "Cabo Verde", "Cape Verde")
_register("CW", "Curacao")
_register("CX", "Christmas Island")
_register("CY", "Cyprus")
_register("CZ", "Czechia", "Czech Republic")
_register("DE", "Germany")
_register("DJ", "Djibouti")
_register("DK", "Denmark")
_register("DM", "Dominica")
_register("DO", "Dominican Republic")
_register("DZ", "Algeria")
_register("EC", "Ecuador")
_register("EE", "Estonia")
_register("EG", "Egypt")
_register("EH", "Western Sahara")
_register("ER", "Eritrea")
_register("ES", "Spain")
_register("ET", "Ethiopia")
_register("FI", "Finland")
_register("FJ", "Fiji")
_register("FK", "Falkland Islands")
_register("FM", "Micronesia")
_register("FO", "Faroe Islands")
_register("FR", "France")
_register("GA", "Gabon")
_register("GB", "United Kingdom", "UK", "Great Britain")
_register("GD", "Grenada")
_register("GE", "Georgia")
_register("GF", "French Guiana")
_register("GG", "Guernsey")
_register("GH", "Ghana")
_register("GI", "Gibraltar")
_register("GL", "Greenland")
_register("GM", "Gambia")
_register("GN", "Guinea")
_register("GP", "Guadeloupe")
_register("GQ", "Equatorial Guinea")
_register("GR", "Greece")
_register("GS", "South Georgia and the South Sandwich Islands")
_register("GT", "Guatemala")
_register("GU", "Guam")
_register("GW", "Guinea-Bissau")
_register("GY", "Guyana")
_register("HK", "Hong Kong")
_register("HM", "Heard Island and McDonald Islands")
_register("HN", "Honduras")
_register("HR", "Croatia")
_register("HT", "Haiti")
_register("HU", "Hungary")
_register("ID", "Indonesia")
_register("IE", "Ireland")
_register("IL", "Israel")
_register("IM", "Isle of Man")
_register("IN", "India")
_register("IO", "British Indian Ocean Territory")
_register("IQ", "Iraq")
_register("IR", "Iran")
_register("IS", "Iceland")
_register("IT", "Italy")
_register("JE", "Jersey")
_register("JM", "Jamaica")
_register("JO", "Jordan")
_register("JP", "Japan")
_register("KE", "Kenya")
_register("KG", "Kyrgyzstan")
_register("KH", "Cambodia")
_register("KI", "Kiribati")
_register("KM", "Comoros")
_register("KN", "Saint Kitts and Nevis")
_register("KP", "North Korea")
_register("KR", "South Korea", "Korea")
_register("KW", "Kuwait")
_register("KY", "Cayman Islands")
_register("KZ", "Kazakhstan")
_register("LA", "Laos")
_register("LB", "Lebanon")
_register("LC", "Saint Lucia")
_register("LI", "Liechtenstein")
_register("LK", "Sri Lanka")
_register("LR", "Liberia")
_register("LS", "Lesotho")
_register("LT", "Lithuania")
_register("LU", "Luxembourg")
_register("LV", "Latvia")
_register("LY", "Libya")
_register("MA", "Morocco")
_register("MC", "Monaco")
_register("MD", "Moldova")
_register("ME", "Montenegro")
_register("MF", "Saint Martin")
_register("MG", "Madagascar")
_register("MH", "Marshall Islands")
_register("MK", "North Macedonia")
_register("ML", "Mali")
_register("MM", "Myanmar", "Burma")
_register("MN", "Mongolia")
_register("MO", "Macao", "Macau")
_register("MP", "Northern Mariana Islands")
_register("MQ", "Martinique")
_register("MR", "Mauritania")
_register("MS", "Montserrat")
_register("MT", "Malta")
_register("MU", "Mauritius")
_register("MV", "Maldives")
_register("MW", "Malawi")
_register("MX", "Mexico")
_register("MY", "Malaysia")
_register("MZ", "Mozambique")
_register("NA", "Namibia")
_register("NC", "New Caledonia")
_register("NE", "Niger")
_register("NF", "Norfolk Island")
_register("NG", "Nigeria")
_register("NI", "Nicaragua")
_register("NL", "Netherlands")
_register("NO", "Norway")
_register("NP", "Nepal")
_register("NR", "Nauru")
_register("NU", "Niue")
_register("NZ", "New Zealand")
_register("OM", "Oman")
_register("PA", "Panama")
_register("PE", "Peru")
_register("PF", "French Polynesia")
_register("PG", "Papua New Guinea")
_register("PH", "Philippines")
_register("PK", "Pakistan")
_register("PL", "Poland")
_register("PM", "Saint Pierre and Miquelon")
_register("PN", "Pitcairn")
_register("PR", "Puerto Rico")
_register("PS", "Palestine")
_register("PT", "Portugal")
_register("PW", "Palau")
_register("PY", "Paraguay")
_register("QA", "Qatar")
_register("RE", "Reunion")
_register("RO", "Romania")
_register("RS", "Serbia")
_register("RU", "Russia", "Russian Federation")
_register("RW", "Rwanda")
_register("SA", "Saudi Arabia")
_register("SB", "Solomon Islands")
_register("SC", "Seychelles")
_register("SD", "Sudan")
_register("SE", "Sweden")
_register("SG", "Singapore")
_register("SH", "Saint Helena")
_register("SI", "Slovenia")
_register("SJ", "Svalbard and Jan Mayen")
_register("SK", "Slovakia")
_register("SL", "Sierra Leone")
_register("SM", "San Marino")
_register("SN", "Senegal")
_register("SO", "Somalia")
_register("SR", "Suriname")
_register("SS", "South Sudan")
_register("ST", "Sao Tome and Principe")
_register("SV", "El Salvador")
_register("SX", "Sint Maarten")
_register("SY", "Syria")
_register("SZ", "Eswatini", "Swaziland")
_register("TC", "Turks and Caicos Islands")
_register("TD", "Chad")
_register("TF", "French Southern Territories")
_register("TG", "Togo")
_register("TH", "Thailand")
_register("TJ", "Tajikistan")
_register("TK", "Tokelau")
_register("TL", "Timor-Leste", "East Timor")
_register("TM", "Turkmenistan")
_register("TN", "Tunisia")
_register("TO", "Tonga")
_register("TR", "Turkey", "Turkiye")
_register("TT", "Trinidad and Tobago")
_register("TV", "Tuvalu")
_register("TW", "Taiwan")
_register("TZ", "Tanzania")
_register("UA", "Ukraine")
_register("UG", "Uganda")
_register("UM", "United States Minor Outlying Islands")
_register("US", "United States", "USA", "United States of America")
_register("UY", "Uruguay")
_register("UZ", "Uzbekistan")
_register("VA", "Vatican City", "Holy See")
_register("VC", "Saint Vincent and the Grenadines")
_register("VE", "Venezuela")
_register("VG", "British Virgin Islands")
_register("VI", "U.S. Virgin Islands", "United States Virgin Islands")
_register("VN", "Vietnam", "Viet Nam")
_register("VU", "Vanuatu")
_register("WF", "Wallis and Futuna")
_register("WS", "Samoa")
_register("YE", "Yemen")
_register("YT", "Mayotte")
_register("ZA", "South Africa")
_register("ZM", "Zambia")
_register("ZW", "Zimbabwe")
